<?php

declare(strict_types=1);

require_once __DIR__ . '/Unit/validation_test.php';
require_once __DIR__ . '/Unit/architecture_baseline_test.php';
require_once __DIR__ . '/Unit/catalog_read_test.php';
require_once __DIR__ . '/Unit/product_write_test.php';
require_once __DIR__ . '/Unit/order_write_test.php';
require_once __DIR__ . '/Unit/order_read_test.php';
require_once __DIR__ . '/Unit/dashboard_test.php';
require_once __DIR__ . '/Unit/people_read_test.php';
require_once __DIR__ . '/Unit/inventory_read_test.php';
require_once __DIR__ . '/Unit/inventory_adjustment_test.php';
require_once __DIR__ . '/Unit/auth_extraction_test.php';
require_once __DIR__ . '/Unit/deployment_test.php';
require_once __DIR__ . '/Unit/http_harness_test.php';
require_once __DIR__ . '/Unit/repository_security_scan_test.php';
require_once __DIR__ . '/Unit/ci_supply_chain_test.php';
require_once __DIR__ . '/Unit/release_integrity_test.php';
require_once __DIR__ . '/Unit/uploads_test.php';
require_once __DIR__ . '/Unit/category_write_test.php';
require_once __DIR__ . '/Unit/category_delete_test.php';
require_once __DIR__ . '/Unit/customer_mutation_test.php';
require_once __DIR__ . '/Unit/supplier_mutation_test.php';
require_once __DIR__ . '/Unit/facade_closure_test.php';
require_once __DIR__ . '/Unit/dead_code_retirement_test.php';
require_once __DIR__ . '/Unit/css_cleanup_test.php';
require_once __DIR__ . '/Unit/ui_redesign_test.php';
require_once __DIR__ . '/Unit/dashboard_ui_test.php';
require_once __DIR__ . '/Unit/pos_ui_test.php';
require_once __DIR__ . '/Unit/products_inventory_ui_test.php';
require_once __DIR__ . '/Unit/customers_suppliers_categories_ui_test.php';
require_once __DIR__ . '/Unit/order_history_details_ui_test.php';
require_once __DIR__ . '/Unit/thermal_invoice_test.php';
require_once __DIR__ . '/Unit/final_ui_closure_test.php';
require_once __DIR__ . '/Unit/operational_baseline_test.php';
require_once __DIR__ . '/Unit/localhost_readiness_test.php';
require_once __DIR__ . '/Unit/data_volume_readiness_test.php';
require_once __DIR__ . '/Integration/database_test.php';
require_once __DIR__ . '/Integration/backup_restore_test.php';
require_once __DIR__ . '/Integration/operational_test.php';
require_once __DIR__ . '/Integration/export_streaming_test.php';
require_once __DIR__ . '/Integration/dashboard_test.php';
require_once __DIR__ . '/Integration/inventory_read_test.php';
require_once __DIR__ . '/Integration/upload_test.php';
require_once __DIR__ . '/Integration/category_write_test.php';
require_once __DIR__ . '/Integration/category_delete_test.php';
require_once __DIR__ . '/Integration/customer_mutation_test.php';
require_once __DIR__ . '/Integration/supplier_mutation_test.php';
require_once __DIR__ . '/Integration/data_volume_test.php';

$started = microtime(true);

try {
    $unitAssertions = run_unit_tests();
    $architectureAssertions = run_architecture_baseline_unit_tests();
    $catalogAssertions = run_catalog_read_unit_tests();
    $productWriteAssertions = run_product_write_unit_tests();
    $orderWriteAssertions = run_order_write_unit_tests();
    $orderReadAssertions = run_order_read_unit_tests();
    $dashboardAssertions = run_dashboard_unit_tests();
    $peopleAssertions = run_people_read_unit_tests();
    $inventoryAssertions = run_inventory_read_unit_tests();
    $inventoryAdjustmentAssertions = run_inventory_adjustment_unit_tests();
    $authAssertions = run_auth_extraction_unit_tests();
    $deploymentAssertions = run_deployment_unit_tests();
    $httpHarnessAssertions = run_http_harness_unit_tests();
    $securityScanAssertions = run_repository_security_scan_unit_tests();
    $supplyChainAssertions = run_ci_supply_chain_unit_tests();
    $releaseIntegrityAssertions = run_release_integrity_unit_tests();
    $uploadAssertions = run_upload_unit_tests();
    $categoryWriteAssertions = run_category_write_unit_tests();
    $categoryDeleteAssertions = run_category_delete_unit_tests();
    $customerMutationAssertions = run_customer_mutation_unit_tests();
    $supplierMutationAssertions = run_supplier_mutation_unit_tests();
    $facadeClosureAssertions = run_facade_closure_unit_tests();
    $deadCodeRetirementAssertions = run_dead_code_retirement_unit_tests();
    $cssCleanupAssertions = run_css_cleanup_unit_tests();
    $uiRedesignAssertions = run_ui_redesign_unit_tests();
    $dashboardUiAssertions = run_dashboard_ui_unit_tests();
    $posUiAssertions = run_pos_ui_unit_tests();
    $productsInventoryUiAssertions = run_products_inventory_ui_unit_tests();
    $customersSuppliersCategoriesUiAssertions = run_customers_suppliers_categories_ui_unit_tests();
    $orderHistoryDetailsUiAssertions = run_order_history_details_ui_unit_tests();
    $thermalInvoiceAssertions = run_thermal_invoice_unit_tests();
    $finalUiClosureAssertions = run_final_ui_closure_unit_tests();
    $operationalBaselineAssertions = run_operational_baseline_unit_tests();
    $localhostReadinessAssertions = run_localhost_readiness_unit_tests();
    $dataVolumeReadinessAssertions = run_data_volume_readiness_unit_tests();
    $integrationAssertions = run_integration_tests();
    $backupAssertions = run_backup_restore_tests();
    $operationalAssertions = run_operational_tests();
    $exportAssertions = run_export_streaming_tests();
    $dashboardIntegrationAssertions = run_dashboard_integration_tests();
    $inventoryReadIntegrationAssertions = run_inventory_read_integration_tests();
    $uploadIntegrationAssertions = run_upload_integration_tests();
    $categoryWriteIntegrationAssertions = run_category_write_integration_tests();
    $categoryDeleteIntegrationAssertions = run_category_delete_integration_tests();
    $customerMutationIntegrationAssertions = run_customer_mutation_integration_tests();
    $supplierMutationIntegrationAssertions = run_supplier_mutation_integration_tests();
    $dataVolumeAssertions = run_data_volume_integration_tests();
    $totalAssertions = $unitAssertions + $architectureAssertions + $catalogAssertions + $productWriteAssertions + $orderWriteAssertions + $orderReadAssertions + $dashboardAssertions + $peopleAssertions + $inventoryAssertions + $inventoryAdjustmentAssertions + $authAssertions + $deploymentAssertions + $httpHarnessAssertions + $securityScanAssertions + $supplyChainAssertions + $releaseIntegrityAssertions + $uploadAssertions + $categoryWriteAssertions + $categoryDeleteAssertions + $customerMutationAssertions + $supplierMutationAssertions + $facadeClosureAssertions + $deadCodeRetirementAssertions + $cssCleanupAssertions + $uiRedesignAssertions + $dashboardUiAssertions + $posUiAssertions + $productsInventoryUiAssertions + $customersSuppliersCategoriesUiAssertions + $orderHistoryDetailsUiAssertions + $thermalInvoiceAssertions + $finalUiClosureAssertions + $operationalBaselineAssertions + $localhostReadinessAssertions + $dataVolumeReadinessAssertions + $integrationAssertions + $backupAssertions + $operationalAssertions + $exportAssertions + $dashboardIntegrationAssertions + $inventoryReadIntegrationAssertions + $uploadIntegrationAssertions + $categoryWriteIntegrationAssertions + $categoryDeleteIntegrationAssertions + $customerMutationIntegrationAssertions + $supplierMutationIntegrationAssertions + $dataVolumeAssertions;
    $duration = number_format(microtime(true) - $started, 2);
    echo "PASS: {$totalAssertions} assertions (" . ($unitAssertions + $architectureAssertions + $catalogAssertions + $productWriteAssertions + $orderWriteAssertions + $orderReadAssertions + $dashboardAssertions + $peopleAssertions + $inventoryAssertions + $inventoryAdjustmentAssertions + $authAssertions + $deploymentAssertions + $httpHarnessAssertions + $securityScanAssertions + $supplyChainAssertions + $releaseIntegrityAssertions + $uploadAssertions + $categoryWriteAssertions + $categoryDeleteAssertions + $customerMutationAssertions + $supplierMutationAssertions + $facadeClosureAssertions + $deadCodeRetirementAssertions + $cssCleanupAssertions + $uiRedesignAssertions + $dashboardUiAssertions + $posUiAssertions + $productsInventoryUiAssertions + $customersSuppliersCategoriesUiAssertions + $orderHistoryDetailsUiAssertions + $thermalInvoiceAssertions + $finalUiClosureAssertions + $operationalBaselineAssertions + $localhostReadinessAssertions + $dataVolumeReadinessAssertions) . " unit, " .
        ($integrationAssertions + $backupAssertions + $operationalAssertions + $exportAssertions + $dashboardIntegrationAssertions + $inventoryReadIntegrationAssertions + $uploadIntegrationAssertions + $categoryWriteIntegrationAssertions + $categoryDeleteIntegrationAssertions + $customerMutationIntegrationAssertions + $supplierMutationIntegrationAssertions + $dataVolumeAssertions) . " integration) in {$duration}s\n";
    exit(0);
} catch (Throwable $exception) {
    fwrite(STDERR, 'FAIL: ' . $exception->getMessage() . PHP_EOL);
    exit(1);
}
